[package]
name = "mrlog"
version = "0.2.1"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
regex = "1.3.6"
structopt = "0.3.13"

anyhow = "1.0.28"

colored = "1.9.3"

crossbeam-channel="0.4.2"

cpp_demangle = "0.2.14"

[target.'cfg(target_os = "linux")'.dependencies]
object={ version = "0.17.0", default-features = false, features = ["read", "compression"] }
addr2line="0.11.0"
memmap2 = "0.1.0"
gimli = { version = "0.20", default-features = false, features = ["read"] }

rental = "0.5.5"
