[package]
name = "mrlog"
version = "0.1.0"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
regex = "1.3.6"
structopt = "0.3.12"

anyhow = "1.0.27"

colored = "1.9.3"

crossbeam-channel="0.4.2"
